# .github/workflows/scheduled-builds.yml
name: Trigger Simplecast Analytics Update on a CRON Schedule

on:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: "0 0 1-31 * *"
jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        # Hit the webhook endpoint to rebuild  from the "main" branch
        run: curl -X POST -d {} https://www.compressed.fm/api/stats/update
